### ISSUE TITLE
ImportError: No Module named netaddr

### ISSUE THREAD

**Issue by n0brainer** [futureimperfect/futureimperfect_scripts#1]
Tried to run your script to convert a handful of subnets, but it errors out

`$ sudo python cidr_to_range.py [~/Desktop/wirelesscidr.csv] 
Traceback (most recent call last):
  File "cidr_to_range.py", line 7, in <module>
    from netaddr import *
ImportError: No module named netaddr`

I tried with and without the [ ] around the csv file.

**Comment by n0brainer** [comment]
this is for the cidr_to_range script btw

**Comment by futureimperfect** [comment]
Hi @n0brainer,

Can you try installing the `netaddr` module then try again? Something like `pip install netaddr`.

https://pypi.python.org/pypi/netaddr

Thanks.

**Comment by satykumar36** [comment]
> Hi @n0brainer,
> 
> Can you try installing the `netaddr` module then try again? Something like `pip install netaddr`.
> 
> https://pypi.python.org/pypi/netaddr
> 
> Thanks.
Thankyou so much this trick worked......hurrayyyyy

**Comment by betzburger** [comment]
Does not work for me.
I do have netaddr installed. I can call netaddr from the command line without any issues.
Still I get this error in a python script 

  File "test.py", line 1, in <module>
    import netaddr
ImportError: No module named netaddr

And yes. I installed netaddr with 3 different methods:
No. 1 "sudo apt-get install python3-netaddr"
No. 2 "pip install netaddr"
No. 3 I downloaded it from Github and installed it.

As I said. I can start netaddr 0.80 - no problem. But I still have this error.

What is wrong?

**Comment by betzburger** [comment]
OK. Found the mistake. Python 2.x was active which was responsible for this error. Python 3.x worked fine.
